//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CUINamedLookup.h"

@interface CUINamedImage : CUINamedLookup
{
    double _scale;
    struct _cuiniproperties {
        unsigned int isVectorBased:1;
        unsigned int hasSliceInformation:1;
        unsigned int hasAlignmentInformation:1;
        unsigned int resizingMode:2;
        unsigned int templateRenderingMode:3;
        unsigned int exifOrientation:4;
        unsigned int _reserved:20;
    } _imageProperties;
}

@property(readonly, nonatomic) double scale; // @synthesize scale=_scale;
- (CGRect)alphaCroppedRect;
- (CGSize)originalUncroppedSize;
- (CGImageRef)createImageFromPDFRenditionWithScale:(double)arg1;
- (id)baseKey;
- (id)description;
@property(readonly, nonatomic) int exifOrientation;
@property(readonly, nonatomic) BOOL isStructured;
@property(readonly, nonatomic) long long templateRenderingMode;
@property(readonly, nonatomic) BOOL isTemplate;
@property(readonly, nonatomic) BOOL isVectorBased;
@property(readonly, nonatomic) BOOL hasAlignmentInformation;
@property(readonly, nonatomic) BOOL hasSliceInformation;
- (long long)resizingModeWithSubtype:(long long)arg1;
@property(readonly, nonatomic) long long resizingMode;
@property(readonly, nonatomic) int blendMode;
@property(readonly, nonatomic) double opacity;
//@property(readonly, nonatomic) CDStruct_3c058996 alignmentEdgeInsets;
//@property(readonly, nonatomic) CDStruct_3c058996 edgeInsets;
- (double)positionOfSliceBoundary:(unsigned int)arg1;
@property(readonly, nonatomic) long long imageType;
- (long long)graphicsClass;
- (long long)memoryClass;
- (long long)sizeClassVertical;
- (long long)sizeClassHorizontal;
- (unsigned long long)subtype;
- (long long)idiom;
@property(readonly, nonatomic) CGSize size;
@property(readonly, nonatomic) CGImageRef image;
- (void)_cacheRenditionProperties;

@end

